# .github/workflows/test_models.yml

name: Test NEST Models

on:
  push:
    branches: [ '**' ]  # Match all branches
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:


jobs:
  test-nest-models:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install .  # if you have a setup.py or pyproject.toml

    - name: Run model tests
      run: |
        pytest tests/
